#!/bin/sh
#Dependencies: Stopify Racketscript (Racks) NPM Node

STOPRUNTIME='stopify-full.bundle.js'
STOPIFYURL="https://github.com/plasma-umass/Stopify/releases/download/0.7.2/$STOPRUNTIME"
RACKSOUT='js-build'
SRC="$RACKSOUT/modules/"
STOPDIR="node_modules/.bin/stopify"
STOPOUT="stopped.js"

echo "Building $1 to $1_stopped.js"


wget $STOPIFYURL -O $STOPRUNTIME

#run racks
racks -bd $RACKSOUT $1

#install node packages
npm install

#run rollup with babel
rollup "$SRC/$1.js" -o bundle.js -f cjs --config rollup.config.js

#use stopify
$STOPDIR --require-runtime bundle.js $STOPOUT

#beautify the results
js-beautify -r $STOPOUT

#
node "stopped.js"